<x-app-layout>
    <x-slot name="header"><div><div class="text-xs font-bold uppercase tracking-[.2em] text-gold-600">Keamanan & Transparansi</div><h1 class="mt-1 font-display text-3xl font-bold text-blue-950">Penelusuran Audit Log</h1><p class="mt-1 text-sm text-slate-500">Lacak aktivitas pengguna dan perubahan data penting dalam sistem.</p></div></x-slot>

    @php $cards = [['Aktivitas Hari Ini', $summary['today']], ['Perubahan Data', $summary['changes']], ['Total Login', $summary['logins']], ['Seluruh Aktivitas', $summary['total']]]; @endphp
    <section class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($cards as [$label,$value])<article class="rounded-2xl border border-slate-100 bg-white p-5 shadow-soft"><div class="flex items-center justify-between"><div class="text-sm font-semibold text-slate-500">{{ $label }}</div><div class="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-blue-800"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M12 8v4l3 2m6-2a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/></svg></div></div><div class="mt-3 text-3xl font-extrabold text-blue-950">{{ number_format($value) }}</div></article>@endforeach</section>

    <section class="mb-6 rounded-2xl border border-slate-100 bg-white p-5 shadow-soft"><form class="grid gap-4 md:grid-cols-2 xl:grid-cols-7"><label class="xl:col-span-2"><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Pencarian</span><input name="search" value="{{ request('search') }}" placeholder="Deskripsi atau isi perubahan..." class="mt-1.5 w-full"></label><label><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Event</span><select name="event" class="mt-1.5 w-full"><option value="">Semua</option>@foreach(['created'=>'Dibuat','updated'=>'Diperbarui','deleted'=>'Dihapus','login'=>'Masuk Sistem','logout'=>'Keluar Sistem','other'=>'Lainnya'] as $key=>$label)<option value="{{ $key }}" @selected(request('event')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Modul</span><select name="subject_type" class="mt-1.5 w-full"><option value="">Semua</option>@foreach([App\Models\Member::class=>'Anggota',App\Models\Saving::class=>'Simpanan',App\Models\Loan::class=>'Pinjaman',App\Models\Installment::class=>'Angsuran'] as $key=>$label)<option value="{{ $key }}" @selected(request('subject_type')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Pelaku</span><select name="causer_id" class="mt-1.5 w-full"><option value="">Semua</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)request('causer_id')===(string)$user->id)>{{ $user->name }}</option>@endforeach</select></label><label><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Dari</span><input type="date" name="date_from" value="{{ request('date_from') }}" class="mt-1.5 w-full"></label><label><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Sampai</span><input type="date" name="date_to" value="{{ request('date_to') }}" class="mt-1.5 w-full"></label><div class="flex items-end gap-2 xl:col-span-2"><button class="rounded-xl bg-blue-800 px-5 py-3 text-sm font-bold text-white">Terapkan Filter</button><a href="{{ route('audit.index') }}" class="rounded-xl px-4 py-3 text-sm font-bold text-slate-500 hover:bg-slate-100">Reset</a></div></form>@error('date_to')<div class="mt-3 text-sm font-semibold text-rose-700">{{ $message }}</div>@enderror</section>

    <section class="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-soft"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 class="font-display text-lg font-bold text-blue-950">Riwayat Aktivitas</h2><p class="text-xs text-slate-400">{{ number_format($activities->total()) }} aktivitas ditemukan</p></div><div class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">● Pencatatan Aktif</div></div><div class="divide-y divide-slate-100">
        @forelse($activities as $activity)
            @php $label=$service->eventLabel($activity); $colors=match($activity->event){'created'=>'bg-emerald-100 text-emerald-700','updated'=>'bg-amber-100 text-amber-700','deleted'=>'bg-rose-100 text-rose-700',default=>($activity->description==='login'?'bg-blue-100 text-blue-700':'bg-slate-100 text-slate-600')}; @endphp
            <article class="group grid gap-4 px-5 py-4 transition hover:bg-blue-50/30 md:grid-cols-[44px_1fr_auto] md:items-center"><div class="grid h-11 w-11 place-items-center rounded-xl {{ $colors }}"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M12 8v4l3 2m6-2a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/></svg></div><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider {{ $colors }}">{{ $label }}</span><span class="text-xs font-semibold text-slate-400">{{ $service->subjectLabel($activity->subject_type) }} · {{ $service->subjectIdentity($activity) }}</span></div><div class="mt-1.5 truncate text-sm font-bold text-slate-700">{{ $activity->description }}</div><div class="mt-1 text-xs text-slate-400">Oleh <span class="font-semibold text-slate-600">{{ $activity->causer?->name ?? 'Sistem' }}</span> · {{ $activity->created_at->translatedFormat('d M Y, H:i:s') }}</div></div><a href="{{ route('audit.show',$activity) }}" class="rounded-xl border border-slate-200 px-4 py-2 text-center text-xs font-bold text-blue-700 transition group-hover:border-blue-200 group-hover:bg-white">Lihat Detail</a></article>
        @empty<div class="px-5 py-16 text-center"><div class="font-bold text-slate-500">Aktivitas tidak ditemukan</div><div class="mt-1 text-xs text-slate-400">Ubah filter untuk melihat data lainnya.</div></div>@endforelse
    </div><div class="border-t border-slate-100 px-5 py-4">{{ $activities->links() }}</div></section>
</x-app-layout>
