<x-app-layout><x-slot name="header"><h1 class="text-2xl font-bold">{{ $member->exists?'Edit':'Tambah' }} Anggota</h1></x-slot>
<form method="POST" enctype="multipart/form-data" action="{{ $member->exists?route('members.update',$member):route('members.store') }}" class="rounded-2xl bg-white p-6 shadow-sm">@csrf @if($member->exists)@method('PUT')@endif
<div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
@foreach(['nik'=>'NIK (16 digit)','name'=>'Nama lengkap','birth_place'=>'Tempat lahir','whatsapp'=>'WhatsApp','email'=>'Email','occupation'=>'Pekerjaan','district'=>'Kecamatan','regency'=>'Kabupaten/Kota','province'=>'Provinsi'] as $field=>$label)<label class="block"><span class="text-sm font-medium">{{ $label }}</span><input name="{{ $field }}" value="{{ old($field,$member->$field) }}" class="mt-1 w-full rounded-xl border-slate-200" @if(in_array($field,['nik','name','birth_place','whatsapp','district','regency','province'])) required @endif>@error($field)<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>@endforeach
<label><span class="text-sm font-medium">Tanggal lahir</span><input type="date" name="birth_date" value="{{ old('birth_date',$member->birth_date?->format('Y-m-d')) }}" class="mt-1 w-full rounded-xl border-slate-200" required></label>
<label><span class="text-sm font-medium">Jenis kelamin</span><select name="gender" class="mt-1 w-full rounded-xl border-slate-200"><option value="male" @selected(old('gender',$member->gender)==='male')>Laki-laki</option><option value="female" @selected(old('gender',$member->gender)==='female')>Perempuan</option></select></label>
<label><span class="text-sm font-medium">Tanggal bergabung</span><input type="date" name="joined_at" value="{{ old('joined_at',$member->joined_at?->format('Y-m-d')??now()->format('Y-m-d')) }}" class="mt-1 w-full rounded-xl border-slate-200" required></label>
<label><span class="text-sm font-medium">Masa berlaku</span><input type="date" name="valid_until" value="{{ old('valid_until',$member->valid_until?->format('Y-m-d')??now()->addYears(5)->format('Y-m-d')) }}" class="mt-1 w-full rounded-xl border-slate-200" required></label>
<label><span class="text-sm font-medium">Status</span><select name="status" class="mt-1 w-full rounded-xl border-slate-200"><option value="active">Aktif</option><option value="inactive" @selected(old('status',$member->status)==='inactive')>Nonaktif</option></select></label>
<label><span class="text-sm font-medium">Foto (JPG/PNG/WEBP)</span><input type="file" name="photo" accept="image/jpeg,image/png,image/webp" class="mt-1 block w-full text-sm"></label>
<label class="md:col-span-2 xl:col-span-3"><span class="text-sm font-medium">Alamat</span><textarea name="address" class="mt-1 w-full rounded-xl border-slate-200" required>{{ old('address',$member->address) }}</textarea></label></div>
<div class="mt-6 flex justify-end gap-3"><a href="{{ route('members.index') }}" class="rounded-xl px-5 py-3">Batal</a><button class="rounded-xl bg-blue-700 px-6 py-3 font-semibold text-white">Simpan</button></div></form></x-app-layout>
