<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#7f2532"><title>Verifikasi Anggota · {{ $member->member_number }}</title><link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml"><link rel="preconnect" href="https://fonts.bunny.net"><link href="https://fonts.bunny.net/css?family=lora:600,700|manrope:400,500,600,700,800" rel="stylesheet">@vite(['resources/css/app.css'])</head>
<body class="koperasi-pattern grid min-h-screen place-items-center bg-gradient-to-br from-blue-950 via-blue-900 to-blue-700 p-4 font-sans">
    <main class="w-full max-w-md overflow-hidden rounded-3xl border border-white/20 bg-white shadow-2xl">
        <div class="bg-blue-50 px-7 py-5"><div class="flex items-center gap-3"><div class="grid h-11 w-11 place-items-center rounded-xl bg-blue-800 text-white"><x-application-logo class="h-8 w-8" /></div><div><div class="font-display text-lg font-bold text-blue-950">Koperasi Modern</div><div class="text-[10px] font-bold uppercase tracking-[.2em] text-gold-600">Verifikasi Keanggotaan</div></div></div></div>
        <div class="p-7 text-center"><div class="mx-auto h-32 w-28 overflow-hidden rounded-2xl border-4 border-white bg-blue-50 shadow-lg">@if($member->hasStoredPhoto())<img src="{{ $member->photoUrl() }}" class="h-full w-full object-cover" alt="Foto {{ $member->name }}">@else<div class="grid h-full place-items-center text-4xl font-bold text-blue-800">{{ strtoupper(substr($member->name, 0, 1)) }}</div>@endif</div><div class="mt-5 inline-flex items-center gap-2 rounded-full {{ $member->status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700' }} px-3 py-1.5 text-xs font-bold uppercase tracking-wider"><span class="h-2 w-2 rounded-full {{ $member->status === 'active' ? 'bg-emerald-500' : 'bg-rose-500' }}"></span>{{ $member->status === 'active' ? 'Anggota Aktif' : 'Tidak Aktif' }}</div><h1 class="mt-4 font-display text-2xl font-bold text-blue-950">{{ $member->name }}</h1><p class="mt-1 font-mono text-sm font-semibold text-slate-500">{{ $member->member_number }}</p><div class="mt-6 grid grid-cols-2 gap-3 rounded-2xl bg-slate-50 p-4 text-left"><div><div class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Bergabung</div><div class="mt-1 text-sm font-bold text-slate-700">{{ $member->joined_at->translatedFormat('d M Y') }}</div></div><div><div class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Berlaku sampai</div><div class="mt-1 text-sm font-bold text-slate-700">{{ $member->valid_until->translatedFormat('d M Y') }}</div></div></div><p class="mt-5 text-xs leading-relaxed text-slate-400">Data ini terverifikasi langsung dari sistem resmi Koperasi Modern.</p></div>
    </main>
</body>
</html>
