<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-end justify-between gap-4"><div><div class="text-xs font-bold uppercase tracking-[.2em] text-gold-600">Analitik & Dokumentasi</div><h1 class="mt-1 font-display text-3xl font-bold text-blue-950">Pusat Laporan</h1><p class="mt-1 text-sm text-slate-500">Data terstruktur untuk evaluasi dan pengambilan keputusan koperasi.</p></div><div class="flex gap-2"><a href="{{ route('reports.pdf', array_merge(['type' => $type], request()->query())) }}" class="rounded-xl border border-blue-200 bg-white px-4 py-2.5 text-sm font-bold text-blue-800 shadow-sm transition hover:bg-blue-50">Unduh PDF</a><a href="{{ route('reports.excel', array_merge(['type' => $type], request()->query())) }}" class="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:bg-emerald-600">Ekspor Excel</a></div></div></x-slot>

    @php $tabs = ['members' => 'Anggota', 'savings' => 'Simpanan', 'loans' => 'Pinjaman', 'installments' => 'Angsuran', 'transactions' => 'Semua Transaksi']; @endphp
    <nav class="mb-6 flex gap-2 overflow-x-auto rounded-2xl border border-slate-100 bg-white p-2 shadow-soft">@foreach($tabs as $key => $label)<a href="{{ route('reports.index', $key) }}" class="whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold transition {{ $type === $key ? 'bg-blue-800 text-white shadow-md' : 'text-slate-500 hover:bg-blue-50 hover:text-blue-800' }}">{{ $label }}</a>@endforeach</nav>

    <section class="mb-6 rounded-2xl border border-slate-100 bg-white p-5 shadow-soft">
        <form class="grid gap-4 md:grid-cols-2 xl:grid-cols-6">
            <label class="xl:col-span-2"><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Pencarian</span><input name="search" value="{{ request('search') }}" placeholder="Nomor, nama, atau identitas..." class="mt-1.5 w-full"></label>
            <label><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Dari tanggal</span><input type="date" name="date_from" value="{{ request('date_from') }}" class="mt-1.5 w-full"></label>
            <label><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Sampai tanggal</span><input type="date" name="date_to" value="{{ request('date_to') }}" class="mt-1.5 w-full"></label>
            @if(in_array($type, ['members', 'loans']))<label><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Status</span><select name="status" class="mt-1.5 w-full"><option value="">Semua</option>@foreach($type === 'members' ? ['active' => 'Aktif', 'inactive' => 'Nonaktif'] : ['submitted' => 'Diajukan', 'approved' => 'Disetujui', 'rejected' => 'Ditolak', 'disbursed' => 'Dicairkan', 'paid' => 'Lunas'] as $key => $label)<option value="{{ $key }}" @selected(request('status') === $key)>{{ $label }}</option>@endforeach</select></label>@endif
            @if(in_array($type, ['savings', 'transactions']))<label><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Arus</span><select name="direction" class="mt-1.5 w-full"><option value="">Semua</option><option value="deposit" @selected(request('direction') === 'deposit')>Masuk</option><option value="withdrawal" @selected(request('direction') === 'withdrawal')>Keluar</option></select></label>@endif
            @if($type === 'savings')<label><span class="text-xs font-bold uppercase tracking-wider text-slate-500">Jenis simpanan</span><select name="saving_type_id" class="mt-1.5 w-full"><option value="">Semua</option>@foreach($savingTypes as $savingType)<option value="{{ $savingType->id }}" @selected((string) request('saving_type_id') === (string) $savingType->id)>{{ $savingType->name }}</option>@endforeach</select></label>@endif
            <div class="flex items-end gap-2"><button class="rounded-xl bg-blue-800 px-5 py-3 text-sm font-bold text-white">Terapkan</button><a href="{{ route('reports.index', $type) }}" class="rounded-xl px-4 py-3 text-sm font-bold text-slate-500 hover:bg-slate-100">Reset</a></div>
        </form>
        @error('date_to')<div class="mt-3 text-sm font-semibold text-rose-700">{{ $message }}</div>@enderror
    </section>

    <section class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($summary as [$label, $value])<article class="rounded-2xl border border-slate-100 bg-white p-5 shadow-soft"><div class="flex items-center justify-between"><div class="text-sm font-semibold text-slate-500">{{ $label }}</div><div class="h-2.5 w-2.5 rounded-full bg-gold-400"></div></div><div class="mt-2 text-2xl font-extrabold tracking-tight text-blue-950">{{ $value }}</div></article>@endforeach</section>

    <section class="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-soft"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 class="font-display text-lg font-bold text-blue-950">{{ $title }}</h2><p class="text-xs text-slate-400">{{ number_format($rows->total()) }} baris ditemukan</p></div><span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">Diperbarui {{ now()->format('H:i') }}</span></div><div class="overflow-x-auto"><table class="w-full whitespace-nowrap text-sm"><thead><tr>@foreach($headings as $heading)<th class="py-3 text-left">{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse($rows as $row)<tr class="border-t border-slate-100 transition hover:bg-blue-50/40">@foreach($row as $cell)<td class="py-3.5 text-slate-700">{{ $cell }}</td>@endforeach</tr>@empty<tr><td colspan="{{ count($headings) }}" class="py-14 text-center"><div class="font-bold text-slate-500">Data tidak ditemukan</div><div class="mt-1 text-xs text-slate-400">Ubah filter atau periode laporan.</div></td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $rows->links() }}</div></section>
</x-app-layout>
