<x-app-layout>
    <x-slot name="header"><div><h1 class="text-2xl font-bold">Pembayaran Angsuran Ke-{{ $nextNumber }}</h1><div class="font-mono text-sm text-slate-500">{{ $loan->loan_number }}</div></div></x-slot>
    <div class="grid gap-6 lg:grid-cols-3">
        <div class="rounded-2xl bg-gradient-to-br from-blue-950 to-blue-700 p-6 text-white shadow-lg"><div class="text-sm text-blue-200">{{ $loan->member->name }}</div><div class="mt-1 text-xs text-blue-300">{{ $loan->member->member_number }}</div><dl class="mt-6 space-y-4 text-sm"><div><dt class="text-blue-300">Sisa pokok</dt><dd class="text-xl font-bold">Rp {{ number_format($loan->remaining_balance, 0, ',', '.') }}</dd></div><div><dt class="text-blue-300">Sisa bunga</dt><dd class="font-semibold">Rp {{ number_format($remainingInterest, 0, ',', '.') }}</dd></div><div><dt class="text-blue-300">Dicairkan</dt><dd>{{ $loan->disbursed_at->format('d-m-Y') }}</dd></div></dl></div>
        <form method="POST" action="{{ route('installments.store', $loan) }}" class="rounded-2xl bg-white p-6 shadow-sm lg:col-span-2" x-data="{ principal: {{ (float) old('principal_paid', $suggestedPrincipal) }}, interest: {{ (float) old('interest_paid', $suggestedInterest) }}, penalty: {{ (float) old('penalty', 0) }}, rupiah(value) { return new Intl.NumberFormat('id-ID').format(value || 0) } }">@csrf
            @if($errors->any())<div class="mb-5 rounded-xl bg-rose-100 px-4 py-3 text-rose-800"><ul class="list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <div class="grid gap-5 md:grid-cols-2"><label><span class="text-sm font-medium">Tanggal pembayaran</span><input type="date" name="paid_at" value="{{ old('paid_at', now()->format('Y-m-d')) }}" min="{{ $loan->disbursed_at->format('Y-m-d') }}" max="{{ now()->format('Y-m-d') }}" class="mt-1 w-full rounded-xl border-slate-200" required></label><div class="rounded-xl bg-emerald-50 p-4"><div class="text-xs uppercase text-emerald-600">Total diterima</div><div class="mt-1 text-2xl font-bold text-emerald-800">Rp <span x-text="rupiah(principal + interest + penalty)"></span></div></div><label><span class="text-sm font-medium">Pembayaran pokok</span><input type="number" name="principal_paid" x-model.number="principal" min="0" max="{{ $loan->remaining_balance }}" step="0.01" class="mt-1 w-full rounded-xl border-slate-200" required></label><label><span class="text-sm font-medium">Pembayaran bunga</span><input type="number" name="interest_paid" x-model.number="interest" min="0" max="{{ $remainingInterest }}" step="0.01" class="mt-1 w-full rounded-xl border-slate-200" required></label><label><span class="text-sm font-medium">Denda</span><input type="number" name="penalty" x-model.number="penalty" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200" required></label><label><span class="text-sm font-medium">Catatan</span><textarea name="notes" rows="3" maxlength="2000" class="mt-1 w-full rounded-xl border-slate-200">{{ old('notes') }}</textarea></label></div>
            <p class="mt-4 text-sm text-slate-500">Status pinjaman otomatis menjadi lunas setelah seluruh pokok dan bunga dibayar. Denda tidak menambah saldo pinjaman.</p><div class="mt-6 flex justify-end gap-3"><a href="{{ route('loans.show', $loan) }}" class="rounded-xl px-5 py-3">Batal</a><button class="rounded-xl bg-blue-700 px-6 py-3 font-semibold text-white">Catat Pembayaran</button></div>
        </form>
    </div>
</x-app-layout>
