<x-app-layout>
    <x-slot name="header"><h1 class="text-2xl font-bold">Riwayat Angsuran</h1></x-slot>
    @if(session('success'))<div class="mb-4 rounded-xl bg-emerald-100 px-4 py-3 text-emerald-800">{{ session('success') }}</div>@endif
    <div class="rounded-2xl bg-white p-5 shadow-sm">
        <form class="mb-5 flex flex-wrap gap-3"><input name="search" value="{{ request('search') }}" placeholder="Nomor pembayaran, pinjaman, anggota..." class="min-w-64 rounded-xl border-slate-200"><input type="date" name="date_from" value="{{ request('date_from') }}" class="rounded-xl border-slate-200"><input type="date" name="date_to" value="{{ request('date_to') }}" class="rounded-xl border-slate-200"><button class="rounded-xl bg-slate-800 px-4 py-2 text-white">Filter</button><a href="{{ route('installments.index') }}" class="rounded-xl px-4 py-2 text-slate-600">Reset</a></form>
        <div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-left text-slate-500"><tr><th class="py-3">Nomor</th><th>Tanggal</th><th>Anggota</th><th>Angsuran</th><th class="text-right">Pokok</th><th class="text-right">Bunga</th><th class="text-right">Denda</th><th class="text-right">Total</th><th></th></tr></thead><tbody>
            @forelse($installments as $installment)<tr class="border-t"><td class="py-4 font-mono text-xs">{{ $installment->payment_number }}</td><td>{{ $installment->paid_at->format('d-m-Y') }}</td><td><div class="font-semibold">{{ $installment->loan->member->name }}</div><div class="text-xs text-slate-400">{{ $installment->loan->loan_number }}</div></td><td>Ke-{{ $installment->installment_number }}</td><td class="text-right">Rp {{ number_format($installment->principal_paid, 0, ',', '.') }}</td><td class="text-right">Rp {{ number_format($installment->interest_paid, 0, ',', '.') }}</td><td class="text-right text-rose-700">Rp {{ number_format($installment->penalty, 0, ',', '.') }}</td><td class="text-right font-bold">Rp {{ number_format($installment->total_paid, 0, ',', '.') }}</td><td class="text-right"><a href="{{ route('installments.show', $installment) }}" class="font-semibold text-blue-700">Bukti</a></td></tr>
            @empty<tr><td colspan="9" class="py-12 text-center text-slate-400">Belum ada pembayaran angsuran.</td></tr>@endforelse
        </tbody></table></div><div class="mt-5">{{ $installments->links() }}</div>
    </div>
</x-app-layout>
